# Generated by Django 3.0.8 on 2020-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('None', 'None'), ('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], default='None', max_length=10)),
                ('type', models.CharField(choices=[('Select', 'Select'), ('Notes', 'Notes'), ('Books', 'Books'), ('Question Papers', 'Question Papers')], default='Select', max_length=100)),
                ('department', models.CharField(choices=[('None', 'None'), ('CS', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('EC', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering')], default='None', max_length=100)),
                ('file', models.FileField(upload_to='Files/')),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
            ],
        ),
    ]
