# Generated by Django 3.0.8 on 2020-10-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200728_1441'),
        ('resource_portal', '0004_auto_20201021_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
        ),
    ]
