# Generated by Django 3.0.8 on 2020-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_portal', '0005_auto_20201022_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
