# Generated by Django 3.0.8 on 2020-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_portal', '0006_resource_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
