# Generated by Django 3.0.8 on 2020-07-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200725_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('None', 'None'), ('CS', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('EC', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('None', 'None'), ('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('None', 'None'), ('CS', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('EC', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering')], default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
