# Generated by Django 3.0.8 on 2020-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200728_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('CS', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('EC', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering')], max_length=100, null=True),
        ),
    ]
